### ISSUE TITLE
Circular Queue 질문

### ISSUE THREAD

**Issue by socquestion** [ECE4278/lab8#2]
simulation에 있어 Circular queue에 대해 궁금증이 생겨 질문드립니다.
Circular queue는 FIFO Module과 비교되어지고 있는데 어떤 타이밍에 어떤 방식으로 비교되어지는지 알고 싶습니다.
테스트벤치를 열어봐도 Circular queue에 대한 부분을 찾지 못해 질문드립니다.

**Comment by dale40** [comment]
Queue는 first in first out이여서 FIFO나 queue는 동일한 것을 가리키는 다른 이름입니다. 소프트웨어에서는 queue라는 이름이 좀더 많이 쓰이지만 하드웨어는 FIFO 또는 FIFO buffer라는 이름을 좀더 많이 사용됩니다.

FIFO (queue)를 구현하는 방법은 여러가지가 있습니다. 이중에서 SW (FIFO의 최대 depth가 고정된 경우) 또는 HW에서 가장 많이 사용되는 것은 수업에서 배운 circular queue 방식입니다.

Circular queue 이외의 방법으로 FIFO를 구현할 수도 있습니다. 예를 들어 HW에서는 shift register를 통해서 구현할 수도 있습니다.

구현을 circular queue를 사용하던 shift register를 해서 사용하던 외부에 보여지는 타이밍은 같도록 만드는 것이 일반적입니다.

**Comment by socquestion** [comment]
그렇군요 감사합니다 교수님
