### ISSUE TITLE
[No space left on device 문제]

### ISSUE THREAD

**Issue by joamin7563** [ECE4278/lab8#3]
과제를 다시 하려고 lab8 디렉토리를 삭제한 후 git clone을 해주었는데
No space left on device라고 뜨며 git clone이 불가능한 상태입니다.
어떻게 해결을 할 수 있을지 여쭤보고 싶습니다. 
<img width="449" alt="image" src="https://user-images.githubusercontent.com/90236499/201561096-ddeb10d7-52da-4f12-bd28-1a3fda1a1239.png">

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

해당 문제는 서버에 용량 부족으로 발생하는 에러로,
추측으로는 simulation이 돌아가는 과정에서 무한 루프 걸려서 덤프된 파일의 크기가 무한정으로 커져서 생기는 문제로 추정됩니다.

해당 문제에 대해서는 공지사항에 올리겠습니다.

박태원 드림

**Comment by pdtowctor** [comment]
용량을 약간 확보했는데 git clone, 시뮬레이션, 합성하는데 지장이 없는지 확인해보시기 바랍니다.

**Comment by joamin7563** [comment]
죄송합니다 조교님 과제하다가 답장하는 것을 깜박했습니다. 빠른 해결 감사드립니다😀
