### ISSUE TITLE
fifo 관련 질문

### ISSUE THREAD

**Issue by S-JinLee** [ECE4278/lab8#4]
data_n, rdata, rdata_n을 선언하여 wren일 때 _n에 저장, rden일 때 data_n을 rdata_n으로 mux하여 rdata_n을 rdata에 ff방식으로 코드를 작성하였습니다..
이렇게 하니 empty일 때 rdata가 가장 마지막에 읽어온 rdata를 불러와서 0을 출력하지 못하는 중입니다.
혹시 이때 포인터가 어디에 위치해야 0이 나오는지 모르겠어서 질문드립니다.
읽어주셔서 감사합니다!

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

0을 출력 못하는 중인데 0이 나오는지 모르겠다는 부분에서 잘 이해를 못 했습니다. 시뮬레이션 돌렸을 때 뜨는 incorrect 결과를 캡쳐해서 보여주세요.

**Comment by S-JinLee** [comment]
![image](https://user-images.githubusercontent.com/69313699/201838640-f8d09262-79bb-4d3a-a28d-285b8b60912a.png)
말씀하신 캡쳐입니다!

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

우선 현재 캡쳐와 코드로 정확히 어떤 부분때문에 이런 결과를 주는지 알기 어렵지만, 일단 현재 코드상으로 문제가 되는 부분들이 좀 있습니다.

1. data_n에 대입하는 부분이 always_ff에 있는게 타당한지를 생각해보셔야합니다. next signal을 사용해서 베릴로그 코딩을 하는 방식이 묘사되어 있는 ppt를 확인하셔서 다시 생각해보시길 바랍니다.

2. 이게 원인일지는 저도 좀 생각을 해봐야겠지만 rden_i일때 mux을 해야할 필요는 없습니다. (이게 확실히 틀린건지는 저도 좀 생각해봐야하겠습니다.) register retiming 이후에도 mux는 특정 조건에서만 할 이유가 없습니다.

3. 여기서는 원인은 아니겠지만 always_comb 안에 non blocking assignment을 넣는 것은 바람직하지 않습니다.

위의 사항들 확인하셔서 다시 코드를 작성해보시기 바랍니다.

**Comment by dale40** [comment]
data_n을 별개의 F/F으로 만든 것 같은데,
data_n은 별개의 F/F이 아니고 data F/F에 들어가는 입력입니다. 그래서 이를 별개의 F/F으로 만들필요 없고, 별개의 신호로 분리만 하면 됩니다.

**Comment by S-JinLee** [comment]
답변해 주셔서 감사합니다! 말씀해 주신대로 다시 코드를 작성해 보았으나 여전히 0을 읽어오지 못하여 rden이 밀리는 중인데, 저는 ptr 문제라고 생각하여 수정중입니다. 혹시 ptr 문제가 맞는지 알려주시면 감사하겠습니다..
![image](https://user-images.githubusercontent.com/69313699/201911405-f9b34227-191b-46fb-abcf-c29991eea43f.png)

**Comment by dale40** [comment]
rdata_n을 생성하는 부분은 맞았습니다.

문제는 data_n[wrptr_n[....]]  부분을 data_n[wrptr]으로 바꾸면 될 것 같습니다.

**Comment by S-JinLee** [comment]
감사합니다! 0이 안나오는 부분은 empty 조건을 통해 0이 나오도록 하였는데 기존 fifo는 이러한 부분이 없었어서 이렇게 코딩을 하는 것이 바람직한지 궁금합니다!

**Comment by dale40** [comment]
0이 나온다는 부분을 이해 못했습니다.

**Comment by S-JinLee** [comment]
rdata를 다 읽어온 후라 empty 상태여서 0을 출력해야 하는데 마지막 출력한 rdata를 이어서 출력하고 있었습니다. 이를 조건문으로 끊어서 코딩하였습니다

**Comment by dale40** [comment]
empty일 때 0을 출력해도 되고, 마지막 데이터를 내보내도 됩니다.
empty인 경우 consumer가 rdata를 사용하는 것은 허용되지 않습니다.

**Comment by S-JinLee** [comment]
답변 감사합니다!

**Comment by pdtowctor** [comment]
S-JinLee님이 질문하는 내용을 봤을 때, Incorrect일 때 Circular Queue에서의 rdata가 0이었기 때문에 empty이면 0이 나와야한다고 생각하신 것으로 이해합니다.

여기서 empty일 때 0이 나오는 식으로 작성하면 안됩니다. FIFO 테스트벤치 동작을 아주 간단하게 요약하자면 처음에 FIFO의 entry를 0으로 초기화하고, 테스트를 할 rd_en, wr_en, wdata 를 랜덤하게 생성해서 하나의 패킷으로 만드는데, 이렇게 여러 개의 패킷을 생성해서 차례대로 FIFO에 신호로 넣어서 FIFO의 기능을 확인하는 과정입니다. 어떤 패킷에서 wr_en이 1인 경우에는 wptr가 가리키는 FIFO의 한 개의 entry에 쓰여질 것이고, rd_en이 1인 경우에는 rdptr가 가리키는 FIFO의 한 개의 entry를 읽습니다.

만약에 첫번째 패킷이 wr_en이 1이고, 두번째 패킷, 세번째 패킷이 rd_en인 경우에는 세번째 패킷에서는 empty인데 rd_en인 상황이 발생하게 됩니다. 이 때 FIFO의 entry 개수를 고려했을 때 rdptr가 가리키는 곳은 아직 한번도 쓰여진적이 없는 곳을 가리킨 상태일 것이고, 랩 실습 코드 (수정되기 전)으로 따졌을 때에는 해당 부분을 읽게 될 겁니다. 따라서 rdata 결과가 0인 겁니다. 만약에 FIFO에 충분히 데이터들이 쓰고 읽고 과정을 한 경우에는 위와 같이 empty인데 rd_en인 상황이 발생하게 되면 rdptr가 가리키는 곳은 이미 어떤 값으로 쓰여져있을거기 때문에 rdata가 0이라는 보장을 할 수 없습니다. 따라서 empty일 때에는 rdata가 0으로 처리하는 코드는 지금 실습 코드에서는 사용하면 안됩니다.

**Comment by webserver3315** [comment]
![image](https://user-images.githubusercontent.com/55400361/201949995-a6eff34c-8e87-4799-8fbd-a708e4880546.png)
왼쪽그림은 정답파형, 우측그림은 제가 구현한 파형입니다.
차이점은 제 파형은 empty 에서 읽었을 때 0이 아니라 이전 값을 유지하게끔 했습니다.

empty 상태에서 읽는건 client에서 허용되지 않는다고 말씀하셨는데,
그렇다면 functionally Correct 를 테스트할 때, Empty 상태에서 읽느라 오답이 발생한 것은 오답으로 치지 않는다고 이해해도 될까요?
저는 Slack을 0으로 하기 위해 고민하다가, Empty상태에서 읽을 때 0이 아니라 이전값이 그대로 출력되는 식으로 구현을 하긴 했는데, 해당 부분은 상관이 없는 부분인지 알고싶습니다.
감사합니다.

**Comment by pdtowctor** [comment]
> ![image](https://user-images.githubusercontent.com/55400361/201949995-a6eff34c-8e87-4799-8fbd-a708e4880546.png) 왼쪽그림은 정답파형, 우측그림은 제가 구현한 파형입니다. 차이점은 제 파형은 empty 에서 읽었을 때 0이 아니라 이전 값을 유지하게끔 했습니다.
> 
> empty 상태에서 읽는건 client에서 허용되지 않는다고 말씀하셨는데, 그렇다면 functionally Correct 를 테스트할 때, Empty 상태에서 읽느라 오답이 발생한 것은 오답으로 치지 않는다고 이해해도 될까요? 저는 Slack을 0으로 하기 위해 고민하다가, Empty상태에서 읽을 때 0이 아니라 이전값이 그대로 출력되는 식으로 구현을 하긴 했는데, 해당 부분은 상관이 없는 부분인지 알고싶습니다. 감사합니다.

원래 구현하신대로 하시면 됩니다. empty일 때에는 이전 값을 유지하는 것이 맞습니다.

**Comment by webserver3315** [comment]
답변 감사합니다!
