### ISSUE TITLE
No space left on device 문제가 또 발생합니다.

### ISSUE THREAD

**Issue by webserver3315** [ECE4278/lab8#5]
![image](https://user-images.githubusercontent.com/55400361/201793778-fe72d70b-0559-4dab-b7ff-202b17d16a21.png)

안녕하세요.
git clone 도중
/home/SOC16/lab8/.git/refs: No space left on device
라는 에러가 발생했고, vim test.txt를 통해 txt 파일을 생성해보려고 했는데 불가하다는 에러를 받았습니다.
아마 아직 누군가 무한루프 vcd파일을 보유하고 있어서 서버용량이 부족한 것 같은데,
조교님께서 용량확보를 해주신다면 감사하겠습니다.
감사합니다.

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

현재는 용량 문제가 없는 것으로 판단되는데 한 번 다시 시도해보시기 바랍니다. 

그리고 서버에서 SOC수업 외에 다른 수업들도 진행되는데 다른 수업의 실습에 의해서도 서버용량부족 문제를 야기하는 것으로 확인됐습니다. 따라서 해당 이슈가 발생했을 때, 해결하는데 약간 시간이 걸린다는 점 양해 부탁 드립니다.

**Comment by webserver3315** [comment]
답변 감사합니다.
