### ISSUE TITLE
11/14 (월) 강의 녹화 질문

### ISSUE THREAD

**Issue by yerjin** [ECE4278/lab8#6]
안녕하세요. 

다름이 아니라 이번주 월요일 강의 내용을 복습하고 싶은데, 매번 올라오던 녹화 영상이 업로드되지 않아
혹시 업로드해주실 수 있는지 여쭙고자 합니다. 감사합니다.

**Comment by dale40** [comment]
안녕하세요.

업로드가 늦었습니다. 지금 막 올렸습니다.
